title: Minnong's blog
description: A simple Jekyll blog hosted on GitHub Pages.
author: Min Hyeong Lee
baseurl: ""
url: "https://minnong511.github.io"
theme: minima
timezone: Asia/Seoul
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

giscus:
  enabled: true
  repo: "minnong511/minnong511.github.io"
  repo_id: "R_kgDONte4cw"
  category: "General"
  category_id: "DIC_kwDONte4c84C3PLr"
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "top"
  theme: "light"
  lang: "ko"
  loading: "lazy"
